
eureka:
  client:
    serviceUrl:
      defaultZone: http://enerbos-cloud-discovery-service:9001/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://enerbos-cloud-auth-service:9002/uaa/user